### ISSUE TITLE
When I compile with my compiler Vue is undefined

### ISSUE THREAD

**Issue by roarkmccolgan** [BosNaufal/vue-autocomplete#1]
In the vue-autocomlete.vue file line 115:

Vue.transition('showAll',{});
When compiled using Browserify Vue on this line is undefined.

Thanks

**Comment by BosNaufal** [comment]
Hey @roarkmccolgan, Thanks for the issue. 
Have you imported 'vue' module? try to install it..
npm install vue

**Comment by roarkmccolgan** [comment]
Thanks for the quick reply @BosNaufal I have installed and required vue
My js file for the compiler looks like this:
`
var Vue = require('vue');
import VueAutocomplete from './components/vue-autocomplete.vue';
new Vue({
    el: "body",

```
components: {
    VueAutocomplete
},

ready() {
    alert('Vue and Vueify all set to go!');
}
```

});
`

**Comment by BosNaufal** [comment]
Hmm... quite tough, Hey @roarkmccolgan. try to make your Vue variable become global.

``` javascript
var Vue = require('vue');
global.Vue = Vue
import VueAutocomplete from './components/vue-autocomplete.vue';
new Vue({
  el: "body",

  components: {
    VueAutocomplete
  },

  ready() {
    alert('Vue and Vueify all set to go!');
  }
});
```

**Comment by roarkmccolgan** [comment]
It is weird, even with global.Vue = Vue; when the component loads, Vue is undefined.
I've added the Vue.transition('showAll',{}); line to my main.js file, do you think thats OK?

**Comment by BosNaufal** [comment]
It's oke, no problem. 
or you can add it as Vue transition property in vue-autocomplete component  
e.g.

``` javascript
// in vue-autocomplete.vue
export default {
...
  transition: {
   showAll(){
      //blablabla
    }
  }
...
};
```

**Comment by roarkmccolgan** [comment]
Much Better!
Thank you
