### ISSUE TITLE
Problem with Vue Js 2.0

### ISSUE THREAD

**Issue by ludioao** [BosNaufal/vue-autocomplete#10]
Hello

When I intent to use this package with Vue Js 2.0.

I'm getting a lot of errors:
like 

`[Vue warn]: class="autocomplete transition autocomplete-{{ name }}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.`

`id="autocomplete-{{ name }}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.`

`- avoid using JavaScript keyword as property name: "class" in expression :class="class"`

**Comment by BosNaufal** [comment]
Hey @ludioao,
Thanks for giving me an issue~ 
Vue2-autocomplete is in progress. So wait for it :)

**Comment by Fatih90** [comment]
@BosNaufal how long is this gonna take to upgrade ?

**Comment by BosNaufal** [comment]
Hey Guys~ @Fatih90 @ludioao 

Sorry for slow response. But, now you can check my new [vue2-autocomplete](https://github.com/BosNaufal/vue2-autocomplete). 

Just tell me if there's something wrong~ :grin:
