### ISSUE TITLE
Disable browser autocomplete to avoid conflicts

### ISSUE THREAD

**Issue by adamcrown** [BosNaufal/vue-autocomplete#13]
I've noticed some issues with browser-based autocomplete (specifically in latest Chrome) competing with the scripted autocomplete. It seems to require that you actually click the result twice to make the selection stick if the entry matches a browser autocomplete result.

Setting `<input type="text" autocomplete="off"...` fixed it for me.

Note: I tried to setup gulp to make a pull request for this, but `gulp build-js` seemed to be changing more than it should in `build.js`. Maybe because of version differences. Also, I couldn't get it to update `vue-autocomplete.js` and `vue-autocomplete.min.js`. I'm not really a JS developer so I'm probably just missing something obvious. I'd be happy to submit a PR if anyone has any advice for how to properly build the project. Thanks.

**Comment by BosNaufal** [comment]
Hey @adamcrown 
Thank you for giving me an issue~ 
And thank you for giving me the solution too :+1: 

For your issue, it has been added to [vue2-autocomplete](https://github.com/BosNaufal/vue2-autocomplete)
