### ISSUE TITLE
Problem with Autocomplete

### ISSUE THREAD

**Issue by eullercristian** [BosNaufal/vue-autocomplete#2]
Dear, 

When i import the autocomplete in my code, i have the follow errror: Uncaught ReferenceError: Vue is not defined, bellow is my code

`import Vue from 'vue'
import VueResource from 'vue-resource'

Vue.use(VueResource)

import Produto from './components/Produto.vue'
import Autocomplete from './components/Autocomplete.vue'

Vue.component('vc-produto', Produto);
Vue.component('autocomplete', Autocomplete);

document.addEventListener("DOMContentLoaded", function (event) {
    new Vue({
        el: 'body',
        data: {
            title: ''
        }
    })
})`

**Comment by eullercristian** [comment]
Dear, 

Its a excelent component, i liked a lot.

I just send a PR for solve this question above, please check.

See you!

Regards

**Comment by BosNaufal** [comment]
Hey @eullercristian, Thanks for helping me! :smile: 
Hopefully, it can be usefull for you~
