### ISSUE TITLE
Ability to clear input after selected

### ISSUE THREAD

**Issue by roarkmccolgan** [BosNaufal/vue-autocomplete#6]
Hi There,

With the events supplied, I am unable to clear the input field once the user has selected the option:

```
...
model="new_material"
...
```

and in the event:

```
events:{
    'autocomplete-myautocomplete:selected': function(data){
        console.log(data);
        this.new_material=''; //does not clear the input field
    }
},
```

**Comment by BosNaufal** [comment]
Hey @roarkmccolgan, thank you for giving me some issues. But, would you like to reproduce it? so I can observe it deeper. Just make a jsbin or some bin you like. :grin:

**Comment by kreierson** [comment]
I have having the same issue. Were you able to figure it out @roarkmccolgan? My code is below but essentially going about it the same way you are

`<autocomplete
    name="customer"
    class="form-control"
    url="/api/customer"
    anchor="first_name"
    label="email"
    model="newTrip.title">
    </autocomplete>` 

Then when I save my form I clear out the property that is bound to the model prop.
`
 this.newTrip.title = '';
`
However when I open up my form again which contains the autocomplete component, the previous selection is still there.

@BosNaufalh how do we clear out the previous selection?

**Comment by kreierson** [comment]
I added an id attribute to the autocomplete component. Then used Jquery to target the ID and blank out the field. Not ideal but gets me to where I want to be.

```
<autocomplete 
  id="myAutocomplete"
  name="customer" 
  class="form-control" 
  url="/api/customer" 
  anchor="first_name" 
  label="email" 
  model="newTrip.title"
> 
</autocomplete>
```

Then when you want the field to clear do

```
$('#myAutocomplete').val('');
```

**Comment by BosNaufal** [comment]
Hi You All~ @kreierson @roarkmccolgan :smile: 
How do you think if I add some method to clear it? :grin:

**Comment by kreierson** [comment]
Yes that would be great. This is a very easy to use component. I have looked at other autocomplete options and found this to be the best. Thank you for your contribution. I am looking forward to your update!

**Comment by roarkmccolgan** [comment]
I agree! I love the component and and update like that would be greatly
appreciated!

Great work!

**Comment by BosNaufal** [comment]
Hey @kreierson @roarkmccolgan. Please review my last [commit](https://github.com/BosNaufal/vue-autocomplete/commit/2d351f0492a14319ed5513b72290e6f29b42f8ea#diff-ef8c7bfa4b51154f78b20c859a33a5beR176)~ :grin: 
Hope it will work well~

**Comment by kreierson** [comment]
Works great! Thanks a lot for adding that feature! I would say this issue is fixed! I appreciate your work on this.
