### ISSUE TITLE
Minimum length required?

### ISSUE THREAD

**Issue by IntellectProductions** [BosNaufal/vue-autocomplete#7]
Is there a way to make a minimum length required before searching or hitting the url??

And for some odd reason, I cannot seem to get my results to pop up even though the Network tab is showing results are showing from the response...

``` js
<autocomplete
                    id="item_search"
                    class="form-control"
                    name="item_search"
                    placeholder="Start typing item name"
                    url="{{ url('api/items') }}"
                    param="name"
                    limit="10"
                    anchor="value"
                    label="label"
                    model="item_search">
                </autocomplete>

              <pre>@{{ items | json }}</pre>
```

I'm doing this:

``` js
    'autocomplete-item_search:before-ajax': function(data){
        console.log(data);
    },
```

and nothing is logging...

Thanks for any help.

**Comment by BosNaufal** [comment]
Hey @IntellectProductions, thank you for giving me an issue~

I have some questions for you By the way,
Have you put that code in "events" scope?
Would you like to give me a reproduce? so I can find the error. 

For the minimum length feature, probably, you should edit the vue file directly :smile:. Then send me a pull request for the merging :grin: 

Thanks! :D
