### ISSUE TITLE
The demo example is not working

### ISSUE THREAD

**Issue by falko189** [BosNaufal/vue-autocomplete#8]
Hi
thanks for this component

I am tring to use this in my project but I am not sure how the Json should be formatted is there a rule? a vue rule? I am pretty new to vue.js 

Can you help me?

thanks for help

**Comment by BosNaufal** [comment]
Hai @falko189, 
Thank you for sending me an issue~
The demo example is using my local server. So you need to define you local server first. Then try it :grin:

**Comment by falko189** [comment]
Thanks for answering.
Endend up doing in a different way :D My question was what the JSON format tho

**Comment by BosNaufal** [comment]
@falko189 I was mistaken to read your comment :v wkwkwkwkw

By the way, there's no rule of the JSON format. You can specify the [label](https://github.com/BosNaufal/vue-autocomplete#label--description-for-suggestion-list) and [anchor](https://github.com/BosNaufal/vue-autocomplete#anchor--anchor-for-suggestion-list)~
